version: '3.0'
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5005
    command: run -m /models

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "5055:5055"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      #I kept my SSL certs in a certs folder in project directory (Make sure to include this in .gitignore)
      - ./certs:/etc/letsencrypt/live/rasa.robinreynaud.xyz
